baseURL = 'https://www.bardiak.com/'
languageCode = 'en-us'
title = 'Bardia Koopah'
theme = 'academimal'
publishDir = "."


[menu]
  [[menu.main]]
    name = "Personal"
    url = "/personal/"
  [[menu.sidebar]]
    name = "Projects"
    url = "/projects/"
  [[menu.sidebar]]
    name = "Publications"
    url = "/publications/"

[params]
  logo = "bardia-pfp.png"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    

